default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: <%= ENV['db_host'] %>
  user: <%= ENV['db_user'] %>
  password: <%= ENV['db_password'] %>

development:
  <<: *default
  database: geoffrey_turpin

test:
  <<: *default
  database: geoffrey_turpin

production:
  <<: *default
  database: geoffrey_turpin